//  This file was generated by CSLA Object Generator - CslaGenFork v4.3.0
//
// Filename:    HC_VatTuTaiSan_PhieuGiaoNhan_Info
// ObjectType:  HC_VatTuTaiSan_PhieuGiaoNhan_Info
// CSLAType:    EditableChild

using System;
using System.Data;
using System.Data.SqlClient;
using Csla;
using Csla.Data;
using NETLINK.LIB;

namespace ModuleHanhChinh.LIB
{

    /// <summary>
    /// HC_VatTuTaiSan_PhieuGiaoNhan_Info (editable child object).<br/>
    /// This is a generated base class of <see cref="HC_VatTuTaiSan_PhieuGiaoNhan_Info"/> business object.
    /// </summary>
    /// <remarks>
    /// This class is an item of <see cref="HC_VatTuTaiSan_PhieuGiaoNhan_Coll"/> collection.
    /// </remarks>
    [Serializable]
    public partial class HC_VatTuTaiSan_PhieuGiaoNhan_Info : BusinessBase<HC_VatTuTaiSan_PhieuGiaoNhan_Info>
    {

        #region Static Fields

        private static Int64 _lastID;

        #endregion

        #region Business Properties

        /// <summary>
        /// Maintains metadata about <see cref="IDVatTuTaiSan"/> property.
        /// </summary>
        public static readonly PropertyInfo<int?> IDVatTuTaiSanProperty = RegisterProperty<int?>(p => p.IDVatTuTaiSan, "IDVat Tu Tai San");
        /// <summary>
        /// Gets or sets the IDVat Tu Tai San.
        /// </summary>
        /// <value>The IDVat Tu Tai San.</value>
        public int? IDVatTuTaiSan
        {
            get { return GetProperty(IDVatTuTaiSanProperty); }
            set { SetProperty(IDVatTuTaiSanProperty, value); }
        }

        /// <summary>
        /// Maintains metadata about <see cref="IDPhieuGiaoNhan"/> property.
        /// </summary>
        public static readonly PropertyInfo<int?> IDPhieuGiaoNhanProperty = RegisterProperty<int?>(p => p.IDPhieuGiaoNhan, "IDPhieu Giao Nhan");
        /// <summary>
        /// Gets or sets the IDPhieu Giao Nhan.
        /// </summary>
        /// <value>The IDPhieu Giao Nhan.</value>
        public int? IDPhieuGiaoNhan
        {
            get { return GetProperty(IDPhieuGiaoNhanProperty); }
            set { SetProperty(IDPhieuGiaoNhanProperty, value); }
        }

        /// <summary>
        /// Maintains metadata about <see cref="ID"/> property.
        /// </summary>
        public static readonly PropertyInfo<Int64> IDProperty = RegisterProperty<Int64>(p => p.ID, "ID");
        /// <summary>
        /// Gets the ID.
        /// </summary>
        /// <value>The ID.</value>
        public Int64 ID
        {
            get { return GetProperty(IDProperty); }
        }

        #endregion

        #region Factory Methods

        /// <summary>
        /// Factory method. Creates a new <see cref="HC_VatTuTaiSan_PhieuGiaoNhan_Info"/> object.
        /// </summary>
        /// <returns>A reference to the created <see cref="HC_VatTuTaiSan_PhieuGiaoNhan_Info"/> object.</returns>
        internal static HC_VatTuTaiSan_PhieuGiaoNhan_Info NewHC_VatTuTaiSan_PhieuGiaoNhan_Info()
        {
            return DataPortal.CreateChild<HC_VatTuTaiSan_PhieuGiaoNhan_Info>();
        }

        /// <summary>
        /// Factory method. Asynchronously creates a new <see cref="HC_VatTuTaiSan_PhieuGiaoNhan_Info"/> object.
        /// </summary>
        /// <param name="callback">The completion callback method.</param>
        internal static void NewHC_VatTuTaiSan_PhieuGiaoNhan_Info(EventHandler<DataPortalResult<HC_VatTuTaiSan_PhieuGiaoNhan_Info>> callback)
        {
            DataPortal.BeginCreate<HC_VatTuTaiSan_PhieuGiaoNhan_Info>(callback);
        }

        /// <summary>
        /// Factory method. Loads a <see cref="HC_VatTuTaiSan_PhieuGiaoNhan_Info"/> object from the given SafeDataReader.
        /// </summary>
        /// <param name="dr">The SafeDataReader to use.</param>
        /// <returns>A reference to the fetched <see cref="HC_VatTuTaiSan_PhieuGiaoNhan_Info"/> object.</returns>
        internal static HC_VatTuTaiSan_PhieuGiaoNhan_Info GetHC_VatTuTaiSan_PhieuGiaoNhan_Info(SafeDataReader dr)
        {
            HC_VatTuTaiSan_PhieuGiaoNhan_Info obj = new HC_VatTuTaiSan_PhieuGiaoNhan_Info();
            // show the framework that this is a child object
            obj.MarkAsChild();
            obj.Fetch(dr);
            obj.MarkOld();
            // check all object rules and property rules
            obj.BusinessRules.CheckRules();
            return obj;
        }

        #endregion

        #region Constructor

        /// <summary>
        /// Initializes a new instance of the <see cref="HC_VatTuTaiSan_PhieuGiaoNhan_Info"/> class.
        /// </summary>
        /// <remarks> Do not use to create a Csla object. Use factory methods instead.</remarks>
        private HC_VatTuTaiSan_PhieuGiaoNhan_Info()
        {
            // Prevent direct creation

            // show the framework that this is a child object
            MarkAsChild();
        }

        #endregion

        #region Data Access

        /// <summary>
        /// Loads default values for the <see cref="HC_VatTuTaiSan_PhieuGiaoNhan_Info"/> object properties.
        /// </summary>
        [Csla.RunLocal]
        protected override void Child_Create()
        {
            LoadProperty(IDProperty, System.Threading.Interlocked.Decrement(ref _lastID));
            var args = new DataPortalHookArgs();
            OnCreate(args);
            base.Child_Create();
        }

        /// <summary>
        /// Loads a <see cref="HC_VatTuTaiSan_PhieuGiaoNhan_Info"/> object from the given SafeDataReader.
        /// </summary>
        /// <param name="dr">The SafeDataReader to use.</param>
        private void Fetch(SafeDataReader dr)
        {
            // Value properties
            LoadProperty(IDVatTuTaiSanProperty, dr.GetInt32("IDVatTuTaiSan"));
            LoadProperty(IDPhieuGiaoNhanProperty, dr.GetInt32("IDPhieuGiaoNhan"));
            LoadProperty(IDProperty, dr.GetInt64("ID"));
            var args = new DataPortalHookArgs(dr);
            OnFetchRead(args);
        }

        /// <summary>
        /// Inserts a new <see cref="HC_VatTuTaiSan_PhieuGiaoNhan_Info"/> object in the database.
        /// </summary>
        private void Child_Insert()
        {
            using (var ctx = TransactionManager<SqlConnection, SqlTransaction>.GetManager("Connection"))
            {
                using (var cmd = new SqlCommand("dbo.HC_VatTuTaiSan_PhieuGiaoNhan_Info_add", ctx.Connection))
                {
                    cmd.Transaction = ctx.Transaction;
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@IDVatTuTaiSan", ReadProperty(IDVatTuTaiSanProperty) == null ? (object)DBNull.Value : ReadProperty(IDVatTuTaiSanProperty).Value).DbType = DbType.Int32;
                    cmd.Parameters.AddWithValue("@IDPhieuGiaoNhan", ReadProperty(IDPhieuGiaoNhanProperty) == null ? (object)DBNull.Value : ReadProperty(IDPhieuGiaoNhanProperty).Value).DbType = DbType.Int32;
                    cmd.Parameters.AddWithValue("@ID", ReadProperty(IDProperty)).Direction = ParameterDirection.Output;
                    var args = new DataPortalHookArgs(cmd);
                    OnInsertPre(args);
                    cmd.ExecuteNonQuery();
                    OnInsertPost(args);
                    LoadProperty(IDProperty, (long) cmd.Parameters["@ID"].Value);
                }
            }
        }

        /// <summary>
        /// Updates in the database all changes made to the <see cref="HC_VatTuTaiSan_PhieuGiaoNhan_Info"/> object.
        /// </summary>
        private void Child_Update()
        {
            if (!IsDirty)
                return;

            using (var ctx = TransactionManager<SqlConnection, SqlTransaction>.GetManager("Connection"))
            {
                using (var cmd = new SqlCommand("dbo.HC_VatTuTaiSan_PhieuGiaoNhan_Info_update", ctx.Connection))
                {
                    cmd.Transaction = ctx.Transaction;
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@IDVatTuTaiSan", ReadProperty(IDVatTuTaiSanProperty) == null ? (object)DBNull.Value : ReadProperty(IDVatTuTaiSanProperty).Value).DbType = DbType.Int32;
                    cmd.Parameters.AddWithValue("@IDPhieuGiaoNhan", ReadProperty(IDPhieuGiaoNhanProperty) == null ? (object)DBNull.Value : ReadProperty(IDPhieuGiaoNhanProperty).Value).DbType = DbType.Int32;
                    cmd.Parameters.AddWithValue("@ID", ReadProperty(IDProperty)).DbType = DbType.Int64;
                    var args = new DataPortalHookArgs(cmd);
                    OnUpdatePre(args);
                    cmd.ExecuteNonQuery();
                    OnUpdatePost(args);
                }
            }
        }

        /// <summary>
        /// Self deletes the <see cref="HC_VatTuTaiSan_PhieuGiaoNhan_Info"/> object from database.
        /// </summary>
        private void Child_DeleteSelf()
        {
            using (var ctx = TransactionManager<SqlConnection, SqlTransaction>.GetManager("Connection"))
            {
                using (var cmd = new SqlCommand("dbo.HC_VatTuTaiSan_PhieuGiaoNhan_Info_delete", ctx.Connection))
                {
                    cmd.Transaction = ctx.Transaction;
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@ID", ReadProperty(IDProperty)).DbType = DbType.Int64;
                    var args = new DataPortalHookArgs(cmd);
                    OnDeletePre(args);
                    cmd.ExecuteNonQuery();
                    OnDeletePost(args);
                }
            }
        }

        #endregion

        #region Pseudo Events

        /// <summary>
        /// Occurs after setting all defaults for object creation.
        /// </summary>
        partial void OnCreate(DataPortalHookArgs args);

        /// <summary>
        /// Occurs in DataPortal_Delete, after setting query parameters and before the delete operation.
        /// </summary>
        partial void OnDeletePre(DataPortalHookArgs args);

        /// <summary>
        /// Occurs in DataPortal_Delete, after the delete operation, before Commit().
        /// </summary>
        partial void OnDeletePost(DataPortalHookArgs args);

        /// <summary>
        /// Occurs after setting query parameters and before the fetch operation.
        /// </summary>
        partial void OnFetchPre(DataPortalHookArgs args);

        /// <summary>
        /// Occurs after the fetch operation (object or collection is fully loaded and set up).
        /// </summary>
        partial void OnFetchPost(DataPortalHookArgs args);

        /// <summary>
        /// Occurs after the low level fetch operation, before the data reader is destroyed.
        /// </summary>
        partial void OnFetchRead(DataPortalHookArgs args);

        /// <summary>
        /// Occurs after setting query parameters and before the update operation.
        /// </summary>
        partial void OnUpdatePre(DataPortalHookArgs args);

        /// <summary>
        /// Occurs in DataPortal_Insert, after the update operation, before setting back row identifiers (RowVersion) and Commit().
        /// </summary>
        partial void OnUpdatePost(DataPortalHookArgs args);

        /// <summary>
        /// Occurs in DataPortal_Insert, after setting query parameters and before the insert operation.
        /// </summary>
        partial void OnInsertPre(DataPortalHookArgs args);

        /// <summary>
        /// Occurs in DataPortal_Insert, after the insert operation, before setting back row identifiers (ID and RowVersion) and Commit().
        /// </summary>
        partial void OnInsertPost(DataPortalHookArgs args);

        #endregion

    }
}
