//  This file was generated by CSLA Object Generator - CslaGenFork v4.3.0
//
// Filename:    TT_AnPham
// ObjectType:  TT_AnPham
// CSLAType:    EditableRoot

using System;
using System.Data;
using System.Data.SqlClient;
using Csla;
using Csla.Data;

namespace TruyenThong.LIB
{

    /// <summary>
    /// TT_AnPham (editable root object).<br/>
    /// This is a generated base class of <see cref="TT_AnPham"/> business object.
    /// </summary>
    [Serializable]
    public partial class TT_AnPham : BusinessBase<TT_AnPham>
    {

        #region Static Fields

        private static Int64 _lastID;

        #endregion

        #region Business Properties

        /// <summary>
        /// Maintains metadata about <see cref="ID"/> property.
        /// </summary>
        public static readonly PropertyInfo<Int64> IDProperty = RegisterProperty<Int64>(p => p.ID, "ID");
        /// <summary>
        /// Gets the ID.
        /// </summary>
        /// <value>The ID.</value>
        public Int64 ID
        {
            get { return GetProperty(IDProperty); }
        }

        /// <summary>
        /// Maintains metadata about <see cref="Ten"/> property.
        /// </summary>
        public static readonly PropertyInfo<string> TenProperty = RegisterProperty<string>(p => p.Ten, "Ten");
        /// <summary>
        /// Gets or sets the Ten.
        /// </summary>
        /// <value>The Ten.</value>
        public string Ten
        {
            get { return GetProperty(TenProperty); }
            set { SetProperty(TenProperty, value); }
        }

        /// <summary>
        /// Maintains metadata about <see cref="IDLoai"/> property.
        /// </summary>
        public static readonly PropertyInfo<int> IDLoaiProperty = RegisterProperty<int>(p => p.IDLoai, "IDLoai");
        /// <summary>
        /// Gets or sets the IDLoai.
        /// </summary>
        /// <value>The IDLoai.</value>
        public int IDLoai
        {
            get { return GetProperty(IDLoaiProperty); }
            set { SetProperty(IDLoaiProperty, value); }
        }

        /// <summary>
        /// Maintains metadata about <see cref="DonViDat"/> property.
        /// </summary>
        public static readonly PropertyInfo<string> DonViDatProperty = RegisterProperty<string>(p => p.DonViDat, "Don Vi Dat");
        /// <summary>
        /// Gets or sets the Don Vi Dat.
        /// </summary>
        /// <value>The Don Vi Dat.</value>
        public string DonViDat
        {
            get { return GetProperty(DonViDatProperty); }
            set { SetProperty(DonViDatProperty, value); }
        }

        /// <summary>
        /// Maintains metadata about <see cref="NoiDung"/> property.
        /// </summary>
        public static readonly PropertyInfo<string> NoiDungProperty = RegisterProperty<string>(p => p.NoiDung, "Noi Dung");
        /// <summary>
        /// Gets or sets the Noi Dung.
        /// </summary>
        /// <value>The Noi Dung.</value>
        public string NoiDung
        {
            get { return GetProperty(NoiDungProperty); }
            set { SetProperty(NoiDungProperty, value); }
        }

        /// <summary>
        /// Maintains metadata about <see cref="SoLuong"/> property.
        /// </summary>
        public static readonly PropertyInfo<int?> SoLuongProperty = RegisterProperty<int?>(p => p.SoLuong, "So Luong");
        /// <summary>
        /// Gets or sets the So Luong.
        /// </summary>
        /// <value>The So Luong.</value>
        public int? SoLuong
        {
            get { return GetProperty(SoLuongProperty); }
            set { SetProperty(SoLuongProperty, value); }
        }

        /// <summary>
        /// Maintains metadata about <see cref="TuNgay"/> property.
        /// </summary>
        public static readonly PropertyInfo<SmartDate> TuNgayProperty = RegisterProperty<SmartDate>(p => p.TuNgay, "Tu Ngay");
        /// <summary>
        /// Gets or sets the Tu Ngay.
        /// </summary>
        /// <value>The Tu Ngay.</value>
        public string TuNgay
        {
            get { return GetPropertyConvert<SmartDate, String>(TuNgayProperty); }
            set { SetPropertyConvert<SmartDate, String>(TuNgayProperty, value); }
        }

        /// <summary>
        /// Maintains metadata about <see cref="DenNgay"/> property.
        /// </summary>
        public static readonly PropertyInfo<SmartDate> DenNgayProperty = RegisterProperty<SmartDate>(p => p.DenNgay, "Den Ngay");
        /// <summary>
        /// Gets or sets the Den Ngay.
        /// </summary>
        /// <value>The Den Ngay.</value>
        public string DenNgay
        {
            get { return GetPropertyConvert<SmartDate, String>(DenNgayProperty); }
            set { SetPropertyConvert<SmartDate, String>(DenNgayProperty, value); }
        }

        /// <summary>
        /// Maintains metadata about <see cref="GhiChu"/> property.
        /// </summary>
        public static readonly PropertyInfo<string> GhiChuProperty = RegisterProperty<string>(p => p.GhiChu, "Ghi Chu");
        /// <summary>
        /// Gets or sets the Ghi Chu.
        /// </summary>
        /// <value>The Ghi Chu.</value>
        public string GhiChu
        {
            get { return GetProperty(GhiChuProperty); }
            set { SetProperty(GhiChuProperty, value); }
        }

        #endregion

        #region Factory Methods

        /// <summary>
        /// Factory method. Creates a new <see cref="TT_AnPham"/> object.
        /// </summary>
        /// <returns>A reference to the created <see cref="TT_AnPham"/> object.</returns>
        public static TT_AnPham NewTT_AnPham()
        {
            return DataPortal.Create<TT_AnPham>();
        }

        /// <summary>
        /// Factory method. Loads a <see cref="TT_AnPham"/> object, based on given parameters.
        /// </summary>
        /// <param name="id">The ID parameter of the TT_AnPham to fetch.</param>
        /// <returns>A reference to the fetched <see cref="TT_AnPham"/> object.</returns>
        public static TT_AnPham GetTT_AnPham(Int64 id)
        {
            return DataPortal.Fetch<TT_AnPham>(id);
        }

        /// <summary>
        /// Factory method. Deletes a <see cref="TT_AnPham"/> object, based on given parameters.
        /// </summary>
        /// <param name="id">The ID of the TT_AnPham to delete.</param>
        public static void DeleteTT_AnPham(Int64 id)
        {
            DataPortal.Delete<TT_AnPham>(id);
        }

        /// <summary>
        /// Factory method. Asynchronously creates a new <see cref="TT_AnPham"/> object.
        /// </summary>
        /// <param name="callback">The completion callback method.</param>
        public static void NewTT_AnPham(EventHandler<DataPortalResult<TT_AnPham>> callback)
        {
            DataPortal.BeginCreate<TT_AnPham>(callback);
        }

        /// <summary>
        /// Factory method. Asynchronously loads a <see cref="TT_AnPham"/> object, based on given parameters.
        /// </summary>
        /// <param name="id">The ID parameter of the TT_AnPham to fetch.</param>
        /// <param name="callback">The completion callback method.</param>
        public static void GetTT_AnPham(Int64 id, EventHandler<DataPortalResult<TT_AnPham>> callback)
        {
            DataPortal.BeginFetch<TT_AnPham>(id, callback);
        }

        /// <summary>
        /// Factory method. Asynchronously deletes a <see cref="TT_AnPham"/> object, based on given parameters.
        /// </summary>
        /// <param name="id">The ID of the TT_AnPham to delete.</param>
        /// <param name="callback">The completion callback method.</param>
        public static void DeleteTT_AnPham(Int64 id, EventHandler<DataPortalResult<TT_AnPham>> callback)
        {
            DataPortal.BeginDelete<TT_AnPham>(id, callback);
        }

        #endregion

        #region Constructor

        /// <summary>
        /// Initializes a new instance of the <see cref="TT_AnPham"/> class.
        /// </summary>
        /// <remarks> Do not use to create a Csla object. Use factory methods instead.</remarks>
        private TT_AnPham()
        {
            // Prevent direct creation
        }

        #endregion

        #region Data Access

        /// <summary>
        /// Loads default values for the <see cref="TT_AnPham"/> object properties.
        /// </summary>
        [Csla.RunLocal]
        protected override void DataPortal_Create()
        {
            LoadProperty(IDProperty, System.Threading.Interlocked.Decrement(ref _lastID));
            LoadProperty(DonViDatProperty, null);
            LoadProperty(NoiDungProperty, null);
            LoadProperty(TuNgayProperty, null);
            LoadProperty(DenNgayProperty, null);
            LoadProperty(GhiChuProperty, null);
            var args = new DataPortalHookArgs();
            OnCreate(args);
            base.DataPortal_Create();
        }

        /// <summary>
        /// Loads a <see cref="TT_AnPham"/> object from the database, based on given criteria.
        /// </summary>
        /// <param name="id">The ID.</param>
        protected void DataPortal_Fetch(Int64 id)
        {
            using (var ctx = ConnectionManager<SqlConnection>.GetManager("Connection"))
            {
                using (var cmd = new SqlCommand("dbo.TT_AnPham_Get", ctx.Connection))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@ID", id).DbType = DbType.Int64;
                    var args = new DataPortalHookArgs(cmd, id);
                    OnFetchPre(args);
                    Fetch(cmd);
                    OnFetchPost(args);
                }
            }
            // check all object rules and property rules
            BusinessRules.CheckRules();
        }

        private void Fetch(SqlCommand cmd)
        {
            using (var dr = new SafeDataReader(cmd.ExecuteReader()))
            {
                if (dr.Read())
                {
                    Fetch(dr);
                }
            }
        }

        /// <summary>
        /// Loads a <see cref="TT_AnPham"/> object from the given SafeDataReader.
        /// </summary>
        /// <param name="dr">The SafeDataReader to use.</param>
        private void Fetch(SafeDataReader dr)
        {
            // Value properties
            LoadProperty(IDProperty, data.ID);
            LoadProperty(TenProperty, data.Ten);
            LoadProperty(IDLoaiProperty, data.IDLoai);
            LoadProperty(DonViDatProperty, data.DonViDat);
            LoadProperty(NoiDungProperty, data.NoiDung);
            LoadProperty(SoLuongProperty, data.SoLuong);
            LoadProperty(TuNgayProperty, data.TuNgay);
            LoadProperty(DenNgayProperty, data.DenNgay);
            LoadProperty(GhiChuProperty, data.GhiChu);
            var args = new DataPortalHookArgs(dr);
            OnFetchRead(args);
        }

        /// <summary>
        /// Inserts a new <see cref="TT_AnPham"/> object in the database.
        /// </summary>
        protected override void DataPortal_Insert()
        {
            using (var ctx = TransactionManager<SqlConnection, SqlTransaction>.GetManager("Connection"))
            {
                using (var cmd = new SqlCommand("dbo.TT_AnPham_Add", ctx.Connection))
                {
                    cmd.Transaction = ctx.Transaction;
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@ID", ReadProperty(IDProperty)).Direction = ParameterDirection.Output;
                    cmd.Parameters.AddWithValue("@Ten", ReadProperty(TenProperty)).DbType = DbType.String;
                    cmd.Parameters.AddWithValue("@IDLoai", ReadProperty(IDLoaiProperty)).DbType = DbType.Int32;
                    cmd.Parameters.AddWithValue("@DonViDat", ReadProperty(DonViDatProperty) == null ? (object)DBNull.Value : ReadProperty(DonViDatProperty)).DbType = DbType.String;
                    cmd.Parameters.AddWithValue("@NoiDung", ReadProperty(NoiDungProperty) == null ? (object)DBNull.Value : ReadProperty(NoiDungProperty)).DbType = DbType.String;
                    cmd.Parameters.AddWithValue("@SoLuong", ReadProperty(SoLuongProperty) == null ? (object)DBNull.Value : ReadProperty(SoLuongProperty).Value).DbType = DbType.Int32;
                    cmd.Parameters.AddWithValue("@TuNgay", ReadProperty(TuNgayProperty).DBValue).DbType = DbType.DateTime;
                    cmd.Parameters.AddWithValue("@DenNgay", ReadProperty(DenNgayProperty).DBValue).DbType = DbType.DateTime;
                    cmd.Parameters.AddWithValue("@GhiChu", ReadProperty(GhiChuProperty) == null ? (object)DBNull.Value : ReadProperty(GhiChuProperty)).DbType = DbType.String;
                    var args = new DataPortalHookArgs(cmd);
                    OnInsertPre(args);
                    cmd.ExecuteNonQuery();
                    OnInsertPost(args);
                    LoadProperty(IDProperty, (long) cmd.Parameters["@ID"].Value);
                }
                ctx.Commit();
            }
        }

        /// <summary>
        /// Updates in the database all changes made to the <see cref="TT_AnPham"/> object.
        /// </summary>
        protected override void DataPortal_Update()
        {
            using (var ctx = TransactionManager<SqlConnection, SqlTransaction>.GetManager("Connection"))
            {
                using (var cmd = new SqlCommand("dbo.TT_AnPham_Upd", ctx.Connection))
                {
                    cmd.Transaction = ctx.Transaction;
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@ID", ReadProperty(IDProperty)).DbType = DbType.Int64;
                    cmd.Parameters.AddWithValue("@Ten", ReadProperty(TenProperty)).DbType = DbType.String;
                    cmd.Parameters.AddWithValue("@IDLoai", ReadProperty(IDLoaiProperty)).DbType = DbType.Int32;
                    cmd.Parameters.AddWithValue("@DonViDat", ReadProperty(DonViDatProperty) == null ? (object)DBNull.Value : ReadProperty(DonViDatProperty)).DbType = DbType.String;
                    cmd.Parameters.AddWithValue("@NoiDung", ReadProperty(NoiDungProperty) == null ? (object)DBNull.Value : ReadProperty(NoiDungProperty)).DbType = DbType.String;
                    cmd.Parameters.AddWithValue("@SoLuong", ReadProperty(SoLuongProperty) == null ? (object)DBNull.Value : ReadProperty(SoLuongProperty).Value).DbType = DbType.Int32;
                    cmd.Parameters.AddWithValue("@TuNgay", ReadProperty(TuNgayProperty).DBValue).DbType = DbType.DateTime;
                    cmd.Parameters.AddWithValue("@DenNgay", ReadProperty(DenNgayProperty).DBValue).DbType = DbType.DateTime;
                    cmd.Parameters.AddWithValue("@GhiChu", ReadProperty(GhiChuProperty) == null ? (object)DBNull.Value : ReadProperty(GhiChuProperty)).DbType = DbType.String;
                    var args = new DataPortalHookArgs(cmd);
                    OnUpdatePre(args);
                    cmd.ExecuteNonQuery();
                    OnUpdatePost(args);
                }
                ctx.Commit();
            }
        }

        /// <summary>
        /// Self deletes the <see cref="TT_AnPham"/> object.
        /// </summary>
        protected override void DataPortal_DeleteSelf()
        {
            DataPortal_Delete(ID);
        }

        /// <summary>
        /// Deletes the <see cref="TT_AnPham"/> object from database.
        /// </summary>
        /// <param name="id">The delete criteria.</param>
        protected void DataPortal_Delete(Int64 id)
        {
            using (var ctx = TransactionManager<SqlConnection, SqlTransaction>.GetManager("Connection"))
            {
                using (var cmd = new SqlCommand("dbo.TT_AnPham_Delete", ctx.Connection))
                {
                    cmd.Transaction = ctx.Transaction;
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@ID", id).DbType = DbType.Int64;
                    var args = new DataPortalHookArgs(cmd, id);
                    OnDeletePre(args);
                    cmd.ExecuteNonQuery();
                    OnDeletePost(args);
                }
                ctx.Commit();
            }
        }

        #endregion

        #region Pseudo Events

        /// <summary>
        /// Occurs after setting all defaults for object creation.
        /// </summary>
        partial void OnCreate(DataPortalHookArgs args);

        /// <summary>
        /// Occurs in DataPortal_Delete, after setting query parameters and before the delete operation.
        /// </summary>
        partial void OnDeletePre(DataPortalHookArgs args);

        /// <summary>
        /// Occurs in DataPortal_Delete, after the delete operation, before Commit().
        /// </summary>
        partial void OnDeletePost(DataPortalHookArgs args);

        /// <summary>
        /// Occurs after setting query parameters and before the fetch operation.
        /// </summary>
        partial void OnFetchPre(DataPortalHookArgs args);

        /// <summary>
        /// Occurs after the fetch operation (object or collection is fully loaded and set up).
        /// </summary>
        partial void OnFetchPost(DataPortalHookArgs args);

        /// <summary>
        /// Occurs after the low level fetch operation, before the data reader is destroyed.
        /// </summary>
        partial void OnFetchRead(DataPortalHookArgs args);

        /// <summary>
        /// Occurs after setting query parameters and before the update operation.
        /// </summary>
        partial void OnUpdatePre(DataPortalHookArgs args);

        /// <summary>
        /// Occurs in DataPortal_Insert, after the update operation, before setting back row identifiers (RowVersion) and Commit().
        /// </summary>
        partial void OnUpdatePost(DataPortalHookArgs args);

        /// <summary>
        /// Occurs in DataPortal_Insert, after setting query parameters and before the insert operation.
        /// </summary>
        partial void OnInsertPre(DataPortalHookArgs args);

        /// <summary>
        /// Occurs in DataPortal_Insert, after the insert operation, before setting back row identifiers (ID and RowVersion) and Commit().
        /// </summary>
        partial void OnInsertPost(DataPortalHookArgs args);

        #endregion

    }
}
