namespace DanhMuc.UserControl
{
    partial class HocHam
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewCheckBoxColumn gridViewCheckBoxColumn1 = new Telerik.WinControls.UI.GridViewCheckBoxColumn();
            this.radgHocHam = new Telerik.WinControls.UI.RadGridView();
            this.bindHocHam = new System.Windows.Forms.BindingSource(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.radgHocHam)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radgHocHam.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bindHocHam)).BeginInit();
            this.SuspendLayout();
            // 
            // radgHocHam
            // 
            this.radgHocHam.BackColor = System.Drawing.SystemColors.Control;
            this.radgHocHam.Cursor = System.Windows.Forms.Cursors.Default;
            this.radgHocHam.Dock = System.Windows.Forms.DockStyle.Fill;
            this.radgHocHam.Font = new System.Drawing.Font("Times New Roman", 12F);
            this.radgHocHam.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radgHocHam.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.radgHocHam.Location = new System.Drawing.Point(0, 28);
            // 
            // radgHocHam
            // 
            this.radgHocHam.MasterTemplate.AllowAddNewRow = false;
            this.radgHocHam.MasterTemplate.AutoSizeColumnsMode = Telerik.WinControls.UI.GridViewAutoSizeColumnsMode.Fill;
            gridViewDecimalColumn1.DataType = typeof(int);
            gridViewDecimalColumn1.EnableExpressionEditor = false;
            gridViewDecimalColumn1.FieldName = "ID";
            gridViewDecimalColumn1.HeaderText = "ID";
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.IsVisible = false;
            gridViewDecimalColumn1.Name = "ID";
            gridViewDecimalColumn1.ReadOnly = true;
            gridViewTextBoxColumn1.EnableExpressionEditor = false;
            gridViewTextBoxColumn1.FieldName = "TenHocHam";
            gridViewTextBoxColumn1.FormatString = "";
            gridViewTextBoxColumn1.HeaderText = "Tên Học Hàm";
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.MaxLength = 50;
            gridViewTextBoxColumn1.Name = "TenHocHam";
            gridViewTextBoxColumn1.Width = 255;
            gridViewCheckBoxColumn1.DataType = typeof(System.Nullable<bool>);
            gridViewCheckBoxColumn1.EnableExpressionEditor = false;
            gridViewCheckBoxColumn1.FieldName = "SuDung";
            gridViewCheckBoxColumn1.FormatString = "";
            gridViewCheckBoxColumn1.HeaderText = "Sử Dụng";
            gridViewCheckBoxColumn1.IsAutoGenerated = true;
            gridViewCheckBoxColumn1.MaxWidth = 90;
            gridViewCheckBoxColumn1.MinWidth = 90;
            gridViewCheckBoxColumn1.Name = "SuDung";
            gridViewCheckBoxColumn1.Width = 90;
            this.radgHocHam.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn1,
            gridViewTextBoxColumn1,
            gridViewCheckBoxColumn1});
            this.radgHocHam.MasterTemplate.DataSource = this.bindHocHam;
            this.radgHocHam.MasterTemplate.EnableFiltering = true;
            this.radgHocHam.Name = "radgHocHam";
            this.radgHocHam.ReadOnly = true;
            this.radgHocHam.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.radgHocHam.Size = new System.Drawing.Size(365, 291);
            this.radgHocHam.TabIndex = 1;
            this.radgHocHam.Text = "radGridView1";
            this.radgHocHam.CellFormatting += new Telerik.WinControls.UI.CellFormattingEventHandler(this.CellFormatting);
            this.radgHocHam.CellDoubleClick += new Telerik.WinControls.UI.GridViewCellEventHandler(this.radgHocHam_CellDoubleClick);
            // 
            // bindHocHam
            // 
            this.bindHocHam.DataSource = typeof(DanhMuc.LIB.DIC_HocHam_Coll);
            // 
            // HocHam
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.radgHocHam);
            this.Name = "HocHam";
            this.Controls.SetChildIndex(this.radgHocHam, 0);
            ((System.ComponentModel.ISupportInitialize)(this.radgHocHam.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radgHocHam)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bindHocHam)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Telerik.WinControls.UI.RadGridView radgHocHam;
        private System.Windows.Forms.BindingSource bindHocHam;
    }
}
