namespace DanhMuc.UserControl
{
    partial class HocVi
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewCheckBoxColumn gridViewCheckBoxColumn1 = new Telerik.WinControls.UI.GridViewCheckBoxColumn();
            this.radgHocVi = new Telerik.WinControls.UI.RadGridView();
            this.bindHocVi = new System.Windows.Forms.BindingSource(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.radgHocVi)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radgHocVi.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bindHocVi)).BeginInit();
            this.SuspendLayout();
            // 
            // radgHocVi
            // 
            this.radgHocVi.BackColor = System.Drawing.SystemColors.Control;
            this.radgHocVi.Cursor = System.Windows.Forms.Cursors.Default;
            this.radgHocVi.Dock = System.Windows.Forms.DockStyle.Fill;
            this.radgHocVi.Font = new System.Drawing.Font("Times New Roman", 12F);
            this.radgHocVi.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radgHocVi.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.radgHocVi.Location = new System.Drawing.Point(0, 61);
            // 
            // radgHocVi
            // 
            this.radgHocVi.MasterTemplate.AllowAddNewRow = false;
            this.radgHocVi.MasterTemplate.AutoSizeColumnsMode = Telerik.WinControls.UI.GridViewAutoSizeColumnsMode.Fill;
            gridViewDecimalColumn1.DataType = typeof(int);
            gridViewDecimalColumn1.EnableExpressionEditor = false;
            gridViewDecimalColumn1.FieldName = "ID";
            gridViewDecimalColumn1.HeaderText = "ID";
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.IsVisible = false;
            gridViewDecimalColumn1.Name = "ID";
            gridViewDecimalColumn1.ReadOnly = true;
            gridViewTextBoxColumn1.EnableExpressionEditor = false;
            gridViewTextBoxColumn1.FieldName = "TenHocVi";
            gridViewTextBoxColumn1.HeaderText = "Tên Học Vị";
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.MaxLength = 50;
            gridViewTextBoxColumn1.Name = "TenHocVi";
            gridViewTextBoxColumn1.Width = 843;
            gridViewTextBoxColumn2.EnableExpressionEditor = false;
            gridViewTextBoxColumn2.FieldName = "TenTat";
            gridViewTextBoxColumn2.HeaderText = "Tên tắt";
            gridViewTextBoxColumn2.Name = "TenTat";
            gridViewTextBoxColumn2.Width = 188;
            gridViewCheckBoxColumn1.DataType = typeof(System.Nullable<bool>);
            gridViewCheckBoxColumn1.EnableExpressionEditor = false;
            gridViewCheckBoxColumn1.FieldName = "SuDung";
            gridViewCheckBoxColumn1.HeaderText = "Sử Dụng";
            gridViewCheckBoxColumn1.IsAutoGenerated = true;
            gridViewCheckBoxColumn1.MaxWidth = 90;
            gridViewCheckBoxColumn1.MinWidth = 90;
            gridViewCheckBoxColumn1.Name = "SuDung";
            gridViewCheckBoxColumn1.Width = 90;
            this.radgHocVi.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn1,
            gridViewTextBoxColumn1,
            gridViewTextBoxColumn2,
            gridViewCheckBoxColumn1});
            this.radgHocVi.MasterTemplate.DataSource = this.bindHocVi;
            this.radgHocVi.MasterTemplate.EnableFiltering = true;
            this.radgHocVi.Name = "radgHocVi";
            this.radgHocVi.ReadOnly = true;
            this.radgHocVi.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.radgHocVi.Size = new System.Drawing.Size(1140, 258);
            this.radgHocVi.TabIndex = 1;
            this.radgHocVi.Text = "radGridView1";
            this.radgHocVi.CellFormatting += new Telerik.WinControls.UI.CellFormattingEventHandler(this.CellFormatting);
            this.radgHocVi.CellDoubleClick += new Telerik.WinControls.UI.GridViewCellEventHandler(this.radgHocVi_CellDoubleClick);
            // 
            // bindHocVi
            // 
            this.bindHocVi.DataSource = typeof(DanhMuc.LIB.DIC_HocVi_Coll);
            // 
            // HocVi
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.radgHocVi);
            this.Name = "HocVi";
            this.Controls.SetChildIndex(this.radgHocVi, 0);
            ((System.ComponentModel.ISupportInitialize)(this.radgHocVi.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radgHocVi)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bindHocVi)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Telerik.WinControls.UI.RadGridView radgHocVi;
        private System.Windows.Forms.BindingSource bindHocVi;
    }
}
