//  This file was generated by CSLA Object Generator - CslaGenFork v4.3.0
//
// Filename:    DIC_CanBo_Coll
// ObjectType:  DIC_CanBo_Coll
// CSLAType:    EditableRootCollection

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using Csla;
using Csla.Data;
using NETLINK.LIB;

namespace DanhMuc.LIB
{

    /// <summary>
    /// DIC_CanBo_Coll (editable root list).<br/>
    /// This is a generated base class of <see cref="DIC_CanBo_Coll"/> business object.
    /// </summary>
    /// <remarks>
    /// The items of the collection are <see cref="DIC_CanBo_Info"/> objects.
    /// </remarks>
    [Serializable]
    public partial class DIC_CanBo_Coll : BusinessBindingListBase<DIC_CanBo_Coll, DIC_CanBo_Info>
    {

        #region Collection Business Methods

        /// <summary>
        /// Removes a <see cref="DIC_CanBo_Info"/> item from the collection.
        /// </summary>
        /// <param name="id">The ID of the item to be removed.</param>
        public void Remove(Int64 id)
        {
            foreach (var dIC_CanBo_Info in this)
            {
                if (dIC_CanBo_Info.ID == id)
                {
                    Remove(dIC_CanBo_Info);
                    break;
                }
            }
        }

        /// <summary>
        /// Determines whether a <see cref="DIC_CanBo_Info"/> item is in the collection.
        /// </summary>
        /// <param name="id">The ID of the item to search for.</param>
        /// <returns><c>true</c> if the DIC_CanBo_Info is a collection item; otherwise, <c>false</c>.</returns>
        public bool Contains(Int64 id)
        {
            foreach (var dIC_CanBo_Info in this)
            {
                if (dIC_CanBo_Info.ID == id)
                {
                    return true;
                }
            }
            return false;
        }

        /// <summary>
        /// Determines whether a <see cref="DIC_CanBo_Info"/> item is in the collection's DeletedList.
        /// </summary>
        /// <param name="id">The ID of the item to search for.</param>
        /// <returns><c>true</c> if the DIC_CanBo_Info is a deleted collection item; otherwise, <c>false</c>.</returns>
        public bool ContainsDeleted(Int64 id)
        {
            foreach (var dIC_CanBo_Info in this.DeletedList)
            {
                if (dIC_CanBo_Info.ID == id)
                {
                    return true;
                }
            }
            return false;
        }

        #endregion

        #region Factory Methods

        /// <summary>
        /// Factory method. Creates a new <see cref="DIC_CanBo_Coll"/> collection.
        /// </summary>
        /// <returns>A reference to the created <see cref="DIC_CanBo_Coll"/> collection.</returns>
        public static DIC_CanBo_Coll NewDIC_CanBo_Coll()
        {
            return DataPortal.Create<DIC_CanBo_Coll>();
        }

        /// <summary>
        /// Factory method. Loads a <see cref="DIC_CanBo_Coll"/> collection.
        /// </summary>
        /// <returns>A reference to the fetched <see cref="DIC_CanBo_Coll"/> collection.</returns>
        public static DIC_CanBo_Coll GetDIC_CanBo_Coll(BusinessFunction function)
        {
            return DataPortal.Fetch<DIC_CanBo_Coll>(function);
        }

        public static DIC_CanBo_Coll GetDIC_CanBo_Coll()
        {
            BusinessFunction function = new BusinessFunction(BusinessFunctionMode.GetDataForGridViewWithCondition);
            function.Item = LoaiCanBo.CanBoThuocTrungTamCDT;
            return DataPortal.Fetch<DIC_CanBo_Coll>(function);
        }

        /// <summary>
        /// Factory method. Asynchronously creates a new <see cref="DIC_CanBo_Coll"/> collection.
        /// </summary>
        /// <param name="callback">The completion callback method.</param>
        public static void NewDIC_CanBo_Coll(EventHandler<DataPortalResult<DIC_CanBo_Coll>> callback)
        {
            DataPortal.BeginCreate<DIC_CanBo_Coll>(callback);
        }

        /// <summary>
        /// Factory method. Asynchronously loads a <see cref="DIC_CanBo_Coll"/> collection.
        /// </summary>
        /// <param name="callback">The completion callback method.</param>
        public static void GetDIC_CanBo_Coll(EventHandler<DataPortalResult<DIC_CanBo_Coll>> callback)
        {
            DataPortal.BeginFetch<DIC_CanBo_Coll>(callback);
        }

        #endregion

        #region Constructor

        /// <summary>
        /// Initializes a new instance of the <see cref="DIC_CanBo_Coll"/> class.
        /// </summary>
        /// <remarks> Do not use to create a Csla object. Use factory methods instead.</remarks>
        private DIC_CanBo_Coll()
        {
            // Prevent direct creation

            var rlce = RaiseListChangedEvents;
            RaiseListChangedEvents = false;
            AllowNew = true;
            AllowEdit = true;
            AllowRemove = true;
            RaiseListChangedEvents = rlce;
        }

        #endregion

        #region Data Access

        /// <summary>
        /// Loads a <see cref="DIC_CanBo_Coll"/> collection from the database.
        /// </summary>
        protected void DataPortal_Fetch(BusinessFunction function)
        {

            using (var ctx = ConnectionManager<SqlConnection>.GetManager("Connection"))
            {
               
                    using (var cmd = new SqlCommand("dbo.DIC_CanBo_Coll_getWithCanBoTypeIncludeIDUser", ctx.Connection))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@Type", Convert.ToInt32(function.Item)).DbType = DbType.Int32;
                        var args = new DataPortalHookArgs(cmd);
                        OnFetchPre(args);
                        LoadCollection(cmd, function);
                        OnFetchPost(args);
                    }
              
            }
        }

        private void LoadCollection(SqlCommand cmd, BusinessFunction function)
        {
            using (var dr = new SafeDataReader(cmd.ExecuteReader()))
            {
                Fetch(dr,function);
            }
        }

        /// <summary>
        /// Loads all <see cref="DIC_CanBo_Coll"/> collection items from the given SafeDataReader.
        /// </summary>
        /// <param name="dr">The SafeDataReader to use.</param>
        private void Fetch(SafeDataReader dr, BusinessFunction function)
        {
            var rlce = RaiseListChangedEvents;
            RaiseListChangedEvents = false;
            while (dr.Read())
            {
                Add(DIC_CanBo_Info.GetDIC_CanBo_Info(dr,function));
            }
            RaiseListChangedEvents = rlce;
        }

        /// <summary>
        /// Updates in the database all changes made to the <see cref="DIC_CanBo_Coll"/> object.
        /// </summary>
        protected override void DataPortal_Update()
        {
            using (var ctx = TransactionManager<SqlConnection, SqlTransaction>.GetManager("Connection"))
            {
                base.Child_Update();
                ctx.Commit();
            }
        }

        #endregion

        #region Pseudo Events

        /// <summary>
        /// Occurs after setting query parameters and before the fetch operation.
        /// </summary>
        partial void OnFetchPre(DataPortalHookArgs args);

        /// <summary>
        /// Occurs after the fetch operation (object or collection is fully loaded and set up).
        /// </summary>
        partial void OnFetchPost(DataPortalHookArgs args);

        #endregion

    }
}
