//  This file was generated by CSLA Object Generator - CslaGenFork v4.3.0
//
// Filename:    HC_CongVanDi_NoiNhan_Info
// ObjectType:  HC_CongVanDi_NoiNhan_Info
// CSLAType:    EditableChild

using System;
using System.Data;
using System.Data.SqlClient;
using Csla;
using Csla.Data;
using NETLINK.LIB;

namespace ModuleHanhChinh.LIB
{

    /// <summary>
    /// HC_CongVanDi_NoiNhan_Info (editable child object).<br/>
    /// This is a generated base class of <see cref="HC_CongVanDi_NoiNhan_Info"/> business object.
    /// </summary>
    /// <remarks>
    /// This class is an item of <see cref="HC_CongVanDi_NoiNhan_Coll"/> collection.
    /// </remarks>
    [Serializable]
    public partial class HC_CongVanDi_NoiNhan_Info : BusinessBase<HC_CongVanDi_NoiNhan_Info>
    {

        #region Static Fields

        private static int _lastID;

        #endregion

        #region Business Properties

        /// <summary>
        /// Maintains metadata about <see cref="ID"/> property.
        /// </summary>
        public static readonly PropertyInfo<int> IDProperty = RegisterProperty<int>(p => p.ID, "ID");
        /// <summary>
        /// Gets the ID.
        /// </summary>
        /// <value>The ID.</value>
        public int ID
        {
            get { return GetProperty(IDProperty); }
        }

        /// <summary>
        /// Maintains metadata about <see cref="idBoPhan"/> property.
        /// </summary>
        public static readonly PropertyInfo<int?> IdBoPhanProperty = RegisterProperty<int?>(p => p.IdBoPhan, "id Bo Phan");
        /// <summary>
        /// Gets or sets the id Bo Phan.
        /// </summary>
        /// <value>The id Bo Phan.</value>
        public int? IdBoPhan
        {
            get { return GetProperty(IdBoPhanProperty); }
            set { SetProperty(IdBoPhanProperty, value); }
        }

        /// <summary>
        /// Maintains metadata about <see cref="TenBoPhan"/> property.
        /// </summary>
        public static readonly PropertyInfo<string> TenBoPhanProperty = RegisterProperty<string>(p => p.TenBoPhan, "Ten Bo Phan");
        /// <summary>
        /// Gets or sets the Ten Bo Phan.
        /// </summary>
        /// <value>The Ten Bo Phan.</value>
        public string TenBoPhan
        {
            get { return GetProperty(TenBoPhanProperty); }
            set { SetProperty(TenBoPhanProperty, value); }
        }

        /// <summary>
        /// Maintains metadata about <see cref="idChuyenKhoa"/> property.
        /// </summary>
        public static readonly PropertyInfo<int?> IdChuyenKhoaProperty = RegisterProperty<int?>(p => p.IdChuyenKhoa, "id Chuyen Khoa");
        /// <summary>
        /// Gets or sets the id Chuyen Khoa.
        /// </summary>
        /// <value>The id Chuyen Khoa.</value>
        public int? IdChuyenKhoa
        {
            get { return GetProperty(IdChuyenKhoaProperty); }
            set { SetProperty(IdChuyenKhoaProperty, value); }
        }

        /// <summary>
        /// Maintains metadata about <see cref="TenChuyenKhoa"/> property.
        /// </summary>
        public static readonly PropertyInfo<string> TenChuyenKhoaProperty = RegisterProperty<string>(p => p.TenChuyenKhoa, "Ten Chuyen Khoa");
        /// <summary>
        /// Gets or sets the Ten Chuyen Khoa.
        /// </summary>
        /// <value>The Ten Chuyen Khoa.</value>
        public string TenChuyenKhoa
        {
            get { return GetProperty(TenChuyenKhoaProperty); }
            set { SetProperty(TenChuyenKhoaProperty, value); }
        }

        /// <summary>
        /// Maintains metadata about <see cref="idCongVanDi"/> property.
        /// </summary>
        public static readonly PropertyInfo<int?> IdCongVanDiProperty = RegisterProperty<int?>(p => p.IdCongVanDi, "id Cong Van Di");
        /// <summary>
        /// Gets or sets the id Cong Van Di.
        /// </summary>
        /// <value>The id Cong Van Di.</value>
        public int? IdCongVanDi
        {
            get { return GetProperty(IdCongVanDiProperty); }
            set { SetProperty(IdCongVanDiProperty, value); }
        }

        #endregion

        #region Factory Methods

        /// <summary>
        /// Factory method. Creates a new <see cref="HC_CongVanDi_NoiNhan_Info"/> object.
        /// </summary>
        /// <returns>A reference to the created <see cref="HC_CongVanDi_NoiNhan_Info"/> object.</returns>
        internal static HC_CongVanDi_NoiNhan_Info NewHC_CongVanDi_NoiNhan_Info()
        {
            return DataPortal.CreateChild<HC_CongVanDi_NoiNhan_Info>();
        }

        /// <summary>
        /// Factory method. Asynchronously creates a new <see cref="HC_CongVanDi_NoiNhan_Info"/> object.
        /// </summary>
        /// <param name="callback">The completion callback method.</param>
        internal static void NewHC_CongVanDi_NoiNhan_Info(EventHandler<DataPortalResult<HC_CongVanDi_NoiNhan_Info>> callback)
        {
            DataPortal.BeginCreate<HC_CongVanDi_NoiNhan_Info>(callback);
        }

        /// <summary>
        /// Factory method. Loads a <see cref="HC_CongVanDi_NoiNhan_Info"/> object from the given SafeDataReader.
        /// </summary>
        /// <param name="dr">The SafeDataReader to use.</param>
        /// <returns>A reference to the fetched <see cref="HC_CongVanDi_NoiNhan_Info"/> object.</returns>
        internal static HC_CongVanDi_NoiNhan_Info GetHC_CongVanDi_NoiNhan_Info(SafeDataReader dr)
        {
            HC_CongVanDi_NoiNhan_Info obj = new HC_CongVanDi_NoiNhan_Info();
            // show the framework that this is a child object
            obj.MarkAsChild();
            obj.Fetch(dr);
            obj.MarkOld();
            // check all object rules and property rules
            obj.BusinessRules.CheckRules();
            return obj;
        }

        #endregion

        #region Constructor

        /// <summary>
        /// Initializes a new instance of the <see cref="HC_CongVanDi_NoiNhan_Info"/> class.
        /// </summary>
        /// <remarks> Do not use to create a Csla object. Use factory methods instead.</remarks>
        private HC_CongVanDi_NoiNhan_Info()
        {
            // Prevent direct creation

            // show the framework that this is a child object
            MarkAsChild();
        }

        #endregion

        #region Data Access

        /// <summary>
        /// Loads default values for the <see cref="HC_CongVanDi_NoiNhan_Info"/> object properties.
        /// </summary>
        [Csla.RunLocal]
        protected override void Child_Create()
        {
            LoadProperty(IDProperty, System.Threading.Interlocked.Decrement(ref _lastID));
            LoadProperty(TenBoPhanProperty, null);
            LoadProperty(TenChuyenKhoaProperty, null);
            var args = new DataPortalHookArgs();
            OnCreate(args);
            base.Child_Create();
        }

        /// <summary>
        /// Loads a <see cref="HC_CongVanDi_NoiNhan_Info"/> object from the given SafeDataReader.
        /// </summary>
        /// <param name="dr">The SafeDataReader to use.</param>
        private void Fetch(SafeDataReader dr)
        {
            // Value properties
            LoadProperty(IDProperty, dr.GetInt32("ID"));
            LoadProperty(IdBoPhanProperty, dr.GetInt32("IdBoPhan"));
            LoadProperty(TenBoPhanProperty, dr.GetString("TenBoPhan"));
            //LoadProperty(IdChuyenKhoaProperty, dr.GetInt32("IdChuyenKhoa"));
            //LoadProperty(TenChuyenKhoaProperty, dr.GetString("TenChuyenKhoa"));
            //LoadProperty(IdCongVanDiProperty, dr.GetInt32("IdCongVanDi"));
            var args = new DataPortalHookArgs(dr);
            OnFetchRead(args);
        }

        /// <summary>
        /// Inserts a new <see cref="HC_CongVanDi_NoiNhan_Info"/> object in the database.
        /// </summary>
        private void Child_Insert()
        {
            using (var ctx = TransactionManager<SqlConnection, SqlTransaction>.GetManager("Connection"))
            {
                using (var cmd = new SqlCommand("dbo.HC_CongVanDi_NoiNhan_Info_add", ctx.Connection))
                {
                    cmd.Transaction = ctx.Transaction;
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@ID", ReadProperty(IDProperty)).Direction = ParameterDirection.Output;
                    cmd.Parameters.AddWithValue("@idBoPhan", ReadProperty(IdBoPhanProperty) == null ? (object)DBNull.Value : ReadProperty(IdBoPhanProperty).Value).DbType = DbType.Int32;
                    cmd.Parameters.AddWithValue("@TenBoPhan", ReadProperty(TenBoPhanProperty) == null ? (object)DBNull.Value : ReadProperty(TenBoPhanProperty)).DbType = DbType.String;
                    cmd.Parameters.AddWithValue("@idChuyenKhoa", ReadProperty(IdChuyenKhoaProperty) == null ? (object)DBNull.Value : ReadProperty(IdChuyenKhoaProperty).Value).DbType = DbType.Int32;
                    cmd.Parameters.AddWithValue("@TenChuyenKhoa", ReadProperty(TenChuyenKhoaProperty) == null ? (object)DBNull.Value : ReadProperty(TenChuyenKhoaProperty)).DbType = DbType.String;
                    cmd.Parameters.AddWithValue("@idCongVanDi", ReadProperty(IdCongVanDiProperty) == null ? (object)DBNull.Value : ReadProperty(IdCongVanDiProperty).Value).DbType = DbType.Int32;
                    var args = new DataPortalHookArgs(cmd);
                    OnInsertPre(args);
                    cmd.ExecuteNonQuery();
                    OnInsertPost(args);
                    LoadProperty(IDProperty, (int) cmd.Parameters["@ID"].Value);
                }
            }
        }

        /// <summary>
        /// Updates in the database all changes made to the <see cref="HC_CongVanDi_NoiNhan_Info"/> object.
        /// </summary>
        private void Child_Update()
        {
            if (!IsDirty)
                return;

            using (var ctx = TransactionManager<SqlConnection, SqlTransaction>.GetManager("Connection"))
            {
                using (var cmd = new SqlCommand("dbo.HC_CongVanDi_NoiNhan_Info_update", ctx.Connection))
                {
                    cmd.Transaction = ctx.Transaction;
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@ID", ReadProperty(IDProperty)).DbType = DbType.Int32;
                    cmd.Parameters.AddWithValue("@idBoPhan", ReadProperty(IdBoPhanProperty) == null ? (object)DBNull.Value : ReadProperty(IdBoPhanProperty).Value).DbType = DbType.Int32;
                    cmd.Parameters.AddWithValue("@TenBoPhan", ReadProperty(TenBoPhanProperty) == null ? (object)DBNull.Value : ReadProperty(TenBoPhanProperty)).DbType = DbType.String;
                    cmd.Parameters.AddWithValue("@idChuyenKhoa", ReadProperty(IdChuyenKhoaProperty) == null ? (object)DBNull.Value : ReadProperty(IdChuyenKhoaProperty).Value).DbType = DbType.Int32;
                    cmd.Parameters.AddWithValue("@TenChuyenKhoa", ReadProperty(TenChuyenKhoaProperty) == null ? (object)DBNull.Value : ReadProperty(TenChuyenKhoaProperty)).DbType = DbType.String;
                    cmd.Parameters.AddWithValue("@idCongVanDi", ReadProperty(IdCongVanDiProperty) == null ? (object)DBNull.Value : ReadProperty(IdCongVanDiProperty).Value).DbType = DbType.Int32;
                    var args = new DataPortalHookArgs(cmd);
                    OnUpdatePre(args);
                    cmd.ExecuteNonQuery();
                    OnUpdatePost(args);
                }
            }
        }

        /// <summary>
        /// Self deletes the <see cref="HC_CongVanDi_NoiNhan_Info"/> object from database.
        /// </summary>
        private void Child_DeleteSelf()
        {
            using (var ctx = TransactionManager<SqlConnection, SqlTransaction>.GetManager("Connection"))
            {
                using (var cmd = new SqlCommand("dbo.HC_CongVanDi_NoiNhan_Info_delete", ctx.Connection))
                {
                    cmd.Transaction = ctx.Transaction;
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@ID", ReadProperty(IDProperty)).DbType = DbType.Int32;
                    var args = new DataPortalHookArgs(cmd);
                    OnDeletePre(args);
                    cmd.ExecuteNonQuery();
                    OnDeletePost(args);
                }
            }
        }

        #endregion

        #region Pseudo Events

        /// <summary>
        /// Occurs after setting all defaults for object creation.
        /// </summary>
        partial void OnCreate(DataPortalHookArgs args);

        /// <summary>
        /// Occurs in DataPortal_Delete, after setting query parameters and before the delete operation.
        /// </summary>
        partial void OnDeletePre(DataPortalHookArgs args);

        /// <summary>
        /// Occurs in DataPortal_Delete, after the delete operation, before Commit().
        /// </summary>
        partial void OnDeletePost(DataPortalHookArgs args);

        /// <summary>
        /// Occurs after setting query parameters and before the fetch operation.
        /// </summary>
        partial void OnFetchPre(DataPortalHookArgs args);

        /// <summary>
        /// Occurs after the fetch operation (object or collection is fully loaded and set up).
        /// </summary>
        partial void OnFetchPost(DataPortalHookArgs args);

        /// <summary>
        /// Occurs after the low level fetch operation, before the data reader is destroyed.
        /// </summary>
        partial void OnFetchRead(DataPortalHookArgs args);

        /// <summary>
        /// Occurs after setting query parameters and before the update operation.
        /// </summary>
        partial void OnUpdatePre(DataPortalHookArgs args);

        /// <summary>
        /// Occurs in DataPortal_Insert, after the update operation, before setting back row identifiers (RowVersion) and Commit().
        /// </summary>
        partial void OnUpdatePost(DataPortalHookArgs args);

        /// <summary>
        /// Occurs in DataPortal_Insert, after setting query parameters and before the insert operation.
        /// </summary>
        partial void OnInsertPre(DataPortalHookArgs args);

        /// <summary>
        /// Occurs in DataPortal_Insert, after the insert operation, before setting back row identifiers (ID and RowVersion) and Commit().
        /// </summary>
        partial void OnInsertPost(DataPortalHookArgs args);

        #endregion

    }
}
